server:
  port: 8085
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dheeraj-Khakre/config-server-microservice.git
          default-label: main         # or 'master' if your repo uses that
          clone-on-start: true
          # If your files are in a subfolder, set:
          # search-paths: config      # (optional)
          username: ${GIT_USERNAME:Dheeraj-khakre}
          password: ${GIT_TOKEN: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}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka